import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/global/Navbar";

const inter = Inter({ subsets: ["latin"] });
import { NextUIProvider } from "@nextui-org/react";
import Footer from "./components/global/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
        <body className={inter.className}>
          <Navbar />
          {children}
          <Footer/> 
        </body>
    </html>
  );
}
